### ISSUE TITLE
_viewts and _idts timestamp transmission

### ISSUE THREAD

**Issue by benedict-formigas** [lcuis/matomo_forever#1]
Hi,

refering to [docs](https://developer.matomo.org/api-reference/tracking-api) Matomo expects as data for the parameters _viewts and _idts  an Unix timestamp.  Matomo forever transfers the timestamp in [milliseconds](https://github.com/lcuis/matomo_forever/blob/e482feb0a9d1ac91354d1c51a2e9e49d7f3315e3/lib/matomo_forever.dart#L866), but if im right Unix timestamps are in seconds. Can you please check this?

Best regards

**Comment by lcuis** [comment]
Hello @benedict-formigas , thanks a lot for reporting this! Indeed, Matomo expects Unix timestamps in seconds. I will correct this as soon as possible.

**Comment by lcuis** [comment]
Version 1.0.2+1 corrects this issue for the following fields:
```
_viewts
_idts
_ects
cdt
```

Thanks again @benedict-formigas for reporting this issue!

Can you please close this issue if you confirm this is fixed? Otherwise, I will probably close it myself in a few weeks.

Cheers!
